apiVersion: extensions/v1beta1
kind: Deployment
metadata: {name: redis-go}
spec:
  replicas: 1
  template:
    metadata:
    - labels:
        environment: qa
        name: redis-go
        tier: backend
    spec:
      containers:
      - command: [
          redis-server,
          --appendonly yes,
          '--requirepass XPASSYO',
          --maxmemory 230mb,
          --maxmemory-policy volatile-lru
        ]
        image: redis:3.2.1
        name: redis-go
        ports:
        - {containerPort: 6379}
        resources:
          limits: {cpu: 30m, memory: 256Mi}
          requests: {cpu: 30m, memory: 256Mi}
        volumeMounts:
        - mountPath: /var/lib/redis
          name: redis-go-datastore
      volumes:
      - gcePersistentDisk:
        - fsType: ext4
          pdName: redis-go-disk
        name: redis-go-datastore
